spring:
  application:
    name: zuul
server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    helloworld:
      path: /helloworld/**