server:
  port: 8005
  servlet:
    context-path: /client2

#debug: true

spring:
  applicaion:
    name: oauth2ssoclientupdw
  thymeleaf:
    cache: false

yoloz:
  uploadPath: /tmp

security:
  oauth2:
    client:
      client-id: client2
      client-secret: client2-secret
      access-token-uri: http://192.168.90.124:8003/oauth/token
      user-authorization-uri: http://192.168.90.124:8003/oauth/authorize
    resource:
      jwt:
        key-uri: http://192.168.90.124:8003/oauth/token_key
        key-value: yoloz