server:
  port: 8004
  servlet:
    context-path: /user

#debug: true

spring:
  application:
    name: oauth2ssoclientusermsg
  thymeleaf:
    cache: false

security:
  oauth2:
    client:
      client-id: client1
      client-secret: client1-secret
      access-token-uri: http://127.0.0.1:8003/oauth/token
      user-authorization-uri: http://127.0.0.1:8003/oauth/authorize
    resource:
      jwt:
        key-uri: http://127.0.0.1:8003/oauth/token_key
        key-value: yoloz
